### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by houshuang** [gmcmanus/anki-roam-import#2]
Attached is a deck of cards generated by my Roam db. Tons of false positives - things like documenting Roam syntax, queries, Latex fragments etc. The safest might be to try to choose another syntax which is not widely used... Not easy in practice. One idea I had was << >> ... 
[Selected Notes.apkg.zip](https://github.com/gmcmanus/anki-roam-import/files/4266477/Selected.Notes.apkg.zip)

**Comment by gmcmanus** [comment]
I agree it's annoying for this add-on to import notes you didn't intend to be notes. Note that you can delete the unwanted notes from Anki after import - even if you import your entire Roam database again, it shouldn't import the unwanted notes twice (the add-on remembers what it imported already). This means each false positive you only need to delete once.

Looking at the examples, I see false positives in these categories which I think I can filter out:
- LaTeX ($$)
- Roam commands like :hiccup, :q
- curly brackets in code (single and triple backticks)
- single curly brackets inside double curly brackets like: `{{query: {and: [[TODO]]}}}`
- opening single curly bracket but closing double curly brackets (e.g. `{ {count}}` - for documenting Roam syntax)

There were also some false positives from copy-pasted HTML which I don't think will be easy to filter out.

Also, I much prefer `{this}` to `<<this>>` because if you select some text in Roam and then press the `{` key it wraps the text in curly brackets, but this doesn't work when pressing the `<` key. Does this make a difference to you?

**Comment by gmcmanus** [comment]
The bullet points listed above should all be fixed in the latest version. Let me know if there are any other issues.
